#!/bin/sh
# Generate Grafana contact points and notification policies from .env.
#
# Why this exists instead of ${VAR} interpolation in a committed file:
# Grafana refuses to load a contact point whose url/token is empty, and a
# failed provisioning run crash-loops the container. So a stack with no alert
# channels yet could not start at all. Generating the file means an
# unconfigured channel is ABSENT rather than empty, and Grafana always starts.
#
# POSIX sh on purpose: this runs both on the LXC (bash) and inside the Alpine
# control container (busybox sh).
#
#   ./render-alerting.sh [project_dir]      default: /srv/monitoring
set -eu

PROJECT_DIR="${1:-/srv/monitoring}"
ENV_FILE="${PROJECT_DIR}/.env"
OUT_DIR="${PROJECT_DIR}/config/grafana/provisioning/alerting"
CP="${OUT_DIR}/contact-points.yml"
NP="${OUT_DIR}/notification-policies.yml"

[ -f "$ENV_FILE" ] || { echo "render-alerting: no $ENV_FILE" >&2; exit 1; }
mkdir -p "$OUT_DIR"

env_get() {
  grep -E "^$1=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | sed 's/^"//; s/"$//'
}

NTFY=$(env_get NTFY_URL)
DISCORD=$(env_get DISCORD_WEBHOOK_URL)
TG_TOKEN=$(env_get TELEGRAM_BOT_TOKEN)
TG_CHAT=$(env_get TELEGRAM_CHAT_ID)

HAVE_NTFY=no;    [ -n "$NTFY" ] && HAVE_NTFY=yes
HAVE_DISCORD=no; [ -n "$DISCORD" ] && HAVE_DISCORD=yes
HAVE_TG=no;      [ -n "$TG_TOKEN" ] && [ -n "$TG_CHAT" ] && HAVE_TG=yes

if [ "$HAVE_NTFY" = no ] && [ "$HAVE_DISCORD" = no ] && [ "$HAVE_TG" = no ]; then
  rm -f "$CP" "$NP"
  echo "render-alerting: no channels configured - rules will still load and"
  echo "                 evaluate, they just will not notify anywhere yet."
  exit 0
fi

# ---- contact points -------------------------------------------------------
{
  echo "apiVersion: 1"
  echo ""
  echo "# GENERATED by scripts/render-alerting.sh from .env - do not edit by hand."
  echo "# Re-run that script (or use the control panel) after changing channels."
  echo ""
  echo "contactPoints:"

  # critical-all: every configured channel. If it is worth waking you, it is
  # worth sending three ways - any one of them can be the broken one.
  echo "  - orgId: 1"
  echo "    name: critical-all"
  echo "    receivers:"
  if [ "$HAVE_NTFY" = yes ]; then
    echo "      - uid: hm-crit-ntfy"
    echo "        type: webhook"
    echo "        settings:"
    echo "          url: ${NTFY}"
    echo "          httpMethod: POST"
  fi
  if [ "$HAVE_TG" = yes ]; then
    echo "      - uid: hm-crit-telegram"
    echo "        type: telegram"
    echo "        settings:"
    echo "          bottoken: ${TG_TOKEN}"
    echo "          chatid: \"${TG_CHAT}\""
  fi
  if [ "$HAVE_DISCORD" = yes ]; then
    echo "      - uid: hm-crit-discord"
    echo "        type: discord"
    echo "        settings:"
    echo "          url: ${DISCORD}"
  fi

  if [ "$HAVE_DISCORD" = yes ]; then
    echo "  - orgId: 1"
    echo "    name: discord"
    echo "    receivers:"
    echo "      - uid: hm-discord"
    echo "        type: discord"
    echo "        settings:"
    echo "          url: ${DISCORD}"
  fi
} > "$CP"

# Warnings prefer Discord (history you skim); fall back to everything.
WARN_RECEIVER="critical-all"
[ "$HAVE_DISCORD" = yes ] && WARN_RECEIVER="discord"

# ---- notification policies ------------------------------------------------
cat > "$NP" <<EOF
apiVersion: 1

# GENERATED by scripts/render-alerting.sh from .env - do not edit by hand.

policies:
  - orgId: 1
    receiver: ${WARN_RECEIVER}
    group_by: [alertname, node, guest]
    routes:
      # Wake me up.
      - receiver: critical-all
        object_matchers:
          - ["severity", "=", "critical"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h

      # Look at it this week.
      - receiver: ${WARN_RECEIVER}
        object_matchers:
          - ["severity", "=", "warning"]
        group_wait: 5m
        group_interval: 30m
        repeat_interval: 24h
EOF

CHANNELS=""
[ "$HAVE_NTFY" = yes ]    && CHANNELS="${CHANNELS} ntfy"
[ "$HAVE_TG" = yes ]      && CHANNELS="${CHANNELS} telegram"
[ "$HAVE_DISCORD" = yes ] && CHANNELS="${CHANNELS} discord"
echo "render-alerting: configured ->${CHANNELS}"
